import { Idea } from './types';

export const CATEGORIES = ['SaaS', 'Consumer', 'AI/ML', 'Hardware', 'Marketplace', 'Social', 'DevTools'];

export const MOCK_IDEAS: Idea[] = [
  {
    id: '1',
    title: 'PlantAI',
    tagline: 'The Fitbit for your houseplants.',
    category: 'Consumer',
    tags: ['IoT', 'Sustainability', 'Mobile App'],
    description: 'Houseplants die because people forget to water them or water them too much. Existing sensors are ugly and require complex hubs.',
    solution: 'A tiny, aesthetic biodegradable stick that syncs directly to a phone via BLE. No hub required. AI suggests care routines based on plant type and local weather.',
    businessModel: 'Direct to consumer hardware ($25/sensor) + Premium subscription for "Plant Doctor" diagnostics.',
    targetAudience: 'Urban millennials, plant parents, offices.',
    risks: 'Hardware margins are thin. Connectivity reliability issues.',
    validationGoals: 'Confirm willingness to pay $25 per sensor.',
    upvotes: 342,
    downvotes: 12,
    views: 1205,
    subscribers: 89,
    comments: [
      { id: 'c1', author: 'Sarah J.', text: 'I have killed 3 fiddle leaf figs. I need this.', createdAt: '2023-10-25T10:00:00Z' },
      { id: 'c2', author: 'Davide', text: 'How long does the battery last?', createdAt: '2023-10-25T12:00:00Z', role: 'Engineer' }
    ],
    createdAt: '2023-10-24T10:00:00Z',
    authorName: 'Alex Green',
    status: 'Prototype'
  },
  {
    id: '2',
    title: 'RetroFit',
    tagline: 'Turn any bicycle into an e-bike in 30 seconds.',
    category: 'Hardware',
    tags: ['Mobility', 'Green Tech', 'Hardware'],
    description: 'E-bikes are expensive ($2k+) and heavy. People love their vintage frames but want power for hills.',
    solution: 'A friction-drive unit that clips onto the seat post and drives the rear wheel. Removable for charging and theft prevention.',
    businessModel: 'Hardware sales ($499).',
    targetAudience: 'Commuters, students, vintage bike enthusiasts.',
    risks: 'Safety regulations, tire wear from friction drive.',
    validationGoals: 'Test prototype weight distribution and user installation time.',
    upvotes: 890,
    downvotes: 45,
    views: 5000,
    subscribers: 412,
    comments: [],
    createdAt: '2023-10-20T10:00:00Z',
    authorName: 'Gearhead Inc.',
    status: 'Alpha'
  },
  {
    id: '3',
    title: 'CodeReviewer.ai',
    tagline: 'Instant junior dev code reviews before you push.',
    category: 'DevTools',
    tags: ['B2B', 'Productivity', 'AI'],
    description: 'Senior devs waste hours on trivial code review comments (syntax, style, simple bugs).',
    solution: 'A CLI tool that runs local LLM analysis to catch logical errors and style issues before a PR is even opened.',
    businessModel: 'Freemium (local only) -> Team Plan (Cloud sync + custom rules).',
    targetAudience: 'Engineering teams, CTOs.',
    risks: 'Hallucinations in code suggestions. Data privacy concerns.',
    validationGoals: 'Assess trust levels in AI code review.',
    upvotes: 120,
    downvotes: 8,
    views: 450,
    subscribers: 15,
    comments: [
      { id: 'c3', author: 'TechLead99', text: 'Does this support Rust?', createdAt: '2023-10-26T09:00:00Z' }
    ],
    createdAt: '2023-10-26T10:00:00Z',
    authorName: 'DevFlow',
    status: 'Concept'
  },
  {
    id: '4',
    title: 'LocalChef',
    tagline: 'Airbnb for home-cooked meals.',
    category: 'Marketplace',
    tags: ['Food', 'Social', 'Gig Economy'],
    description: 'Restaurants are expensive and unhealthy. Talented home cooks want to earn money but lack commercial kitchens.',
    solution: 'A platform connecting hungry neighbors with verified home cooks for pickup meals.',
    businessModel: '15% fee on each transaction.',
    targetAudience: 'Busy families, home cooks.',
    risks: 'Massive health department regulatory hurdles. Food safety liability.',
    validationGoals: 'Is this even legal in NYC/SF?',
    upvotes: 56,
    downvotes: 30,
    views: 300,
    subscribers: 5,
    comments: [],
    createdAt: '2023-10-27T10:00:00Z',
    authorName: 'Chef Boyardee',
    status: 'Concept'
  },
  {
    id: '5',
    title: 'Nostalgic',
    tagline: 'Print your Spotify playlists on vinyl.',
    category: 'Consumer',
    tags: ['Music', 'E-commerce', 'Niche'],
    description: 'Digital music feels ephemeral. Vinyl is booming but you can only buy albums.',
    solution: 'On-demand lathe-cut vinyl records of your custom playlists (with rights management cleared).',
    businessModel: 'High margin e-commerce ($50 per record).',
    targetAudience: 'Audiophiles, gift givers.',
    risks: 'Copyright licensing is a nightmare. Lathe cutting is slow.',
    validationGoals: 'Find a licensing partner.',
    upvotes: 1200,
    downvotes: 5,
    views: 8900,
    subscribers: 2000,
    comments: [
      { id: 'c4', author: 'VinylJunkie', text: 'Take my money.', createdAt: '2023-10-20T10:00:00Z' }
    ],
    createdAt: '2023-10-15T10:00:00Z',
    authorName: 'Spin Doctor',
    status: 'Beta'
  },
   {
    id: '6',
    title: 'FreelanceFlow',
    tagline: 'Financial stack for solo-preneurs.',
    category: 'SaaS',
    tags: ['Fintech', 'B2B', 'Productivity'],
    description: 'Freelancers use 5 apps for invoicing, taxes, time tracking, and banking.',
    solution: 'All-in-one financial dashboard tailored for the gig economy.',
    businessModel: 'SaaS subscription $20/mo.',
    targetAudience: 'Designers, Developers, Writers.',
    risks: 'Crowded market (Honeybook, etc).',
    validationGoals: 'Feature parity requirements.',
    upvotes: 45,
    downvotes: 2,
    views: 120,
    subscribers: 12,
    comments: [],
    createdAt: '2023-10-28T10:00:00Z',
    authorName: 'SoloDev',
    status: 'Concept'
  },
   {
    id: '7',
    title: 'WalkMan',
    tagline: 'On-demand dog walking for rural areas.',
    category: 'Marketplace',
    tags: ['Pets', 'Services'],
    description: 'Rover is great for cities, but rural dog owners have no options.',
    solution: 'Hyper-local network of vetted walkers in spread-out communities.',
    businessModel: 'Service fee.',
    targetAudience: 'Rural pet owners.',
    risks: 'Travel time for walkers makes unit economics hard.',
    validationGoals: 'Driver supply.',
    upvotes: 22,
    downvotes: 0,
    views: 80,
    subscribers: 1,
    comments: [],
    createdAt: '2023-10-29T10:00:00Z',
    authorName: 'RuralRover',
    status: 'Concept'
  },
    {
    id: '8',
    title: 'SilentDisco',
    tagline: 'Headphones that sync with venue audio for accessibility.',
    category: 'Hardware',
    tags: ['Accessibility', 'Audio', 'Events'],
    description: 'Concerts are too loud or too quiet for different people.',
    solution: 'Venue-provided headphones that let users control their own volume mix of the live show.',
    businessModel: 'B2B rental to venues.',
    targetAudience: 'Concert halls, festivals.',
    risks: 'Hardware loss/theft.',
    validationGoals: 'Venue interest.',
    upvotes: 156,
    downvotes: 10,
    views: 400,
    subscribers: 45,
    comments: [],
    createdAt: '2023-10-22T10:00:00Z',
    authorName: 'AudioLabs',
    status: 'Prototype'
  }
];